---
language: node_js
node_js:
  - 10.16.0
cache:
  yarn: true
  directories:
    - node_modules

services:
  - mongodb

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash

script:
  - yarn install
  - yarn test
